# Site settings
title: MicaelleOS
baseurl: https://micaelleos.github.io/
url: "https://micaelleos.github.io"
google_analytics: G-R4CWYLGXX1 # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Micaelle O.S.
  desc: Hello, welcome!
  email: micaelle.oliveira10@hotmail.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: https://github.com/micaelleos/
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/micaelle-oliveira-souza/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: 
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/blog/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"

collections:
  certificates:
    permalink: /certificates/:path/
